memo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('memo_app.urls')),
]

memo_app/urls.py
from django.urls import path
from . import views

app_name = 'memo_app'
urlpatterns = [
  path('',views.index,name='index'),
  path('<int:memo_id>',views.detail,name='detail'),
  path('new_memo',views.new_memo,name='new_memo'),
  path('delete_memo/<int:memo_id>',views.delete_memo,name='delete_memo'),
  path('edit_memo/<int:memo_id>',views.edit_memo,name='edit_memo')
]

memo_app/models.py
from django.db import models

# Create your models here.
class Memo(models.Model):
  title = models.CharField(max_length=150)
  text = models.TextField(blank=True)
  created_datetime = models.DateTimeField(auto_now_add=True)
  updated_datetime = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.title

memo_app/forms.py
from django.forms import ModelForm
from .models import Memo

class MemoForm(ModelForm):
  class Meta:
    model = Memo
    fields = ['title','text']

memo_app/views.py
from django.shortcuts import render,redirect
from .models import Memo
from django.shortcuts import get_object_or_404
from .forms import MemoForm
from django.views.decorators.http import require_POST

# Create your views here.
def index(request):
  memos = Memo.objects.all().order_by('-updated_datetime')
  return render(request,'memo_app/memo.html',{'memos':memos})

def detail(request,memo_id):
  memo = get_object_or_404(Memo,id=memo_id)
  return render(request,'memo_app/detail.html',{'memo':memo})

def new_memo(request):
  if request.method == 'POST':
    form = MemoForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect('memo_app:index')
  else:
    form = MemoForm
  return render(request,'memo_app/new_memo.html',{'form':form})

@require_POST
def delete_memo(request,memo_id):
  memo = get_object_or_404(Memo,id=memo_id)
  memo.delete()
  return redirect('memo_app:index')

def edit_memo(request,memo_id):
  memo = get_object_or_404(Memo,id=memo_id)
  if request.method == 'POST':
    form = MemoForm(request.POST,instance=memo)
    if form.is_valid():
      form.save()
      return redirect('memo_app:index')
  else:
    form = MemoForm(instance=memo)
  return render(request,'memo_app/edit_memo.html',{'memo':memo,'form':form})

memo_app/templates/memo_app/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'memo_app/css/style.css'%}">
  <title>Memoアプリ</title>
</head>

<body>
  <h1>Myメモ</h1>

  <div class="container">
    {% block content %}{% endblock %}
  </div>

</body>
</html>

memo_app/templates/memo_app/detail.html
{% extends 'memo_app/base.html' %}

{% block content %}

    <div>
      <a href="{% url 'memo_app:index' %}">ホームに戻る</a>
    </div>
    
    <h2>{{ memo.title }}</h2>
    <div>
      {{ memo.text | linebreaks | urlize }}
    </div>

    <button><a class="btn" href="{% url 'memo_app:edit_memo' memo.id %}">編集</a></button>


    <form method="post" action="{% url 'memo_app:delete_memo' memo.id %}">{% csrf_token %}
      <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
    </form>

{% endblock %}

memo_app/templates/memo_app/edit_memo.html
{% extends 'memo_app/base.html' %}

{% block content %}

    <div>
      <a href="{% url 'memo_app:detail' memo.id %}">戻る</a>
      </div>
      
      <form action="{% url 'memo_app:edit_memo' memo.id %}" method="POST">{% csrf_token %}
        <table>
          <tr>
            <th>タイトル</th>
            <td>{{ form.title }}</td>
          </tr>
          <tr>
            <th>テキスト</th>
            <td>{{ form.text }}</td>
          </tr>
        </table>
        <button class="btn" type="submit">保存</button>
      </form>

{% endblock %}

memo_app/templates/memo_app/memo.html
{% extends 'memo_app/base.html' %}

{% block content %}

    <a class="btn" href="{% url 'memo_app:new_memo' %}">新規メモ作成</a>

    {% for memo in memos %}
    <a href="{% url 'memo_app:detail' memo.id %}" class="memo-title">
      <div>
        {{ memo.title }}
        <span class="updated_datetime">{{ memo.updated_datetime }}</span>
      </div>
    </a>
    {% endfor %}

{% endblock %}

memo_app/templates/memo_app/new_memo.html
{% extends 'memo_app/base.html' %}

{% block content %}

    <div>
      <a href="{% url 'memo_app:index' %}">ホームに戻る</a>
    </div>
    <form action="{% url 'memo_app:new_memo' %}" method="POST">{% csrf_token %}
      <table>
        <tr>
          <th>タイトル</th>
          <td>{{ form.title }}</td>
        </tr>
        <tr>
          <th>テキスト</th>
          <td>{{ form.text }}</td>
        </tr>
      </table>
      <button type="submit" class="btn">保存</button>
    </form>

{% endblock %}